name       : pycanberra
version    : 1
release    : 5
source     :
    - git|https://github.com/totdb/pycanberra.git : 88c53cd44a626ede3b07dab0b548f8bcfda42867
license    : LGPL-2.1
component  : programming.python
summary    : A ctypes wrapper for the libcanberra api
description: |
    A ctypes wrapper for the libcanberra api
builddeps  :
    - pkgconfig(python3)
build      : |
    python3 -c 'import compileall, sys; \
              sys.exit(not \
              compileall.compile_file("pycanberra.py", ddir=".", force=1))'
install    : |
    install -D -d -m 00755 $installdir/usr/lib/python3.6/site-packages
    install -D -d -m 00755 $installdir/usr/share/doc/pycanberra
    install -m 00644 pycanberra.py $installdir/usr/lib/python3.6/site-packages
    install -m 00644 README COPYING $installdir/usr/share/doc/pycanberra
    install -d -m 00755 $installdir/usr/lib/python3.6/site-packages/__pycache__
    install -m 00644 __pycache__/* $installdir/usr/lib/python3.6/site-packages/__pycache__/.
