name       : pycanberra
version    : 1
release    : 2
source     :
    - http://solus-us.tk/sources/63badd5b9737bac519df509dff2ae34c05fa5f2cb5e360897b9a0312256b4a2d/pycanberra.tar.xz : 63badd5b9737bac519df509dff2ae34c05fa5f2cb5e360897b9a0312256b4a2d
license    : LGPL-2.1
summary    : A ctypes wrapper for the libcanberra api
description: |
    A ctypes wrapper for the libcanberra api
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    python -c 'import compileall, sys; \
              sys.exit(not \
              compileall.compile_file("pycanberra.py", ddir=".", force=1))'
install    : |
    mkdir -p %installroot%/usr/lib/python3.4/site-packages
    mkdir -p %installroot%/usr/share/doc/pycanberra
    install -m 0644 pycanberra.py %installroot%/usr/lib/python3.4/site-packages
    cp README COPYING %installroot%/usr/share/doc/pycanberra
